apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  namespace: pos
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
    configmanagement.gke.io/cluster-selector: abm-northamerica-northeast2-sel,continent-north-america-sel,abm-europe-west4-sel,abm-europe-central2-sel,abm-asia-east1-sel,continent-australia-sel,abm-asia-northeast3-sel,abm-europe-southwest1-sel,abm-europe-west8-sel,abm-asia-northeast2-sel,abm-asia-south1-sel,abm-europe-west9-sel,canary-25-sel,abm-us-west3-sel,abm-europe-west6-sel,abm-asia-southeast1-sel,abm-us-west4-sel,abm-us-south1-sel,abm-asia-northeast1-sel,abm-souththamerica-west1-sel,abm-us-west1-sel,abm-us-west2-sel,abm-australia-southeast1-sel,canary-100-sel,continent-south-america-sel,abm-northamerica-northeast1-sel,abm-souththamerica-east1-sel,abm-asia-south2-sel,abm-australia-southeast2-sel,abm-europe-west3-sel,continent-asia-sel,abm-us-east4-sel,continent-usa-sel,abm-asia-southeast2-sel,abm-europe-north1-sel,abm-europe-west1-sel,abm-europe-west2-sel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
      - name: pos
        image: gcr.io/anthos-edge-361104/pos:v2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
        - -nginx.scrape-uri=http://127.0.0.1/nginx_status
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 9113
